### ISSUE TITLE
TODO: Move Constraints from create-post.js to new js files

### ISSUE THREAD

**Issue by agctute** [cse110-fa22-group10/cse110-fa22-group10#68]
## Prerequisites: 

 - #36 
 - #63 
 - #64 
 - #65 

## Context

 - Since we've moved to making post creation pages for each platform, the constraints that Antonio made in ```create-post.js``` need to be moved to each file and updated to only be the constraints for that platform. 

## Description of what's needed

 - Constraints to text applied to each post creation page

## Location

 - ```editPost.js```
 - ```createFb.js```, ```createIns.js```, ```createTw.js```
 - You might have to create the three files above if they don't exist already

**Comment by Yr-Nemsis** [comment]
The issue has already been resolved and create-post.js has been deleted
